AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'apimklc'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'klc-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'klcgithubactions'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'